name: MineResetLite
version: 0.5.0
main: com.koletar.jj.mineresetlite.MineResetLitePlugin
author: Boomclaw
authors: [jjKoletar, VirtualByte, TWWSYesterday, Boomclaw, SprockPls]
description: A lightweight solution for Mine management.
softdepend: [WorldEdit, Multiverse-Core, PrisonMines, Multiworld]
commands:
  mineresetlite:
    aliases: [mrl, mr, mine, minereset]
    description: Manage mines.